PayersPayment/Models/ErrorViewModel.cs
using System;

namespace PayersPayment.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PayersPayment/Models/PayerViewModel.cs
using PayersPayment.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PayersPayment.Models
{
    public class PayerViewModel
    {
        public string Name { get; set; }
        public string Address { get; set;}
        public int  Age { get; set; }
        public GenderEnum Geneder { get; set; }
    }
}

PayersPayment/Models/PayerViewModelList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PayersPayment.Models
{
    public class PayerViewModelList
    {
        public IList<PayerViewModel> Items { get; set; }
    }
}

PayersPayment/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PayersPayment.Models;

namespace PayersPayment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PayersPayment/Controllers/PayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using PayersPayment.Interfaces;
using PayersPayment.Models;
using PayersPayment.Data.Entities;
using PayersPayment.Services;
using System.Web.Mvc;
using System.Net;
using PayersPayment.Data;


namespace PayersPayment.Controllers
{
    public class PayersController : System.Web.Mvc.Controller
    {
        private readonly ILogger<PayersController> _logger;
        private IRepositoryGet<Payer> _repository;

        public PayersController(ILogger<PayersController> logger, IRepositoryGet<Payer> repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public ActionResult Index()
        {
            PayerViewModelList model = new PayerViewModelList { Items = new List<PayerViewModel> { } };

            model.Items = _repository.Get().SelectMany(i => new List<PayerViewModel> { i.Map() }).ToList(); 
            
            return View(model);
        }

        public ActionResult Edit(string name)
        {
            PayerRepository repo = new PayerRepository();
            var payerlist = repo.Get();
            var payer = payerlist.Where(p => p.Name == name).FirstOrDefault();
            return View(name);
        }
    }
}

PayersPayment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3>Welcome on SD coding challange</h3>
</div>
<div class="text-left">
    <p>Thank you very much for taking the time to contribute into SmartDebit code challange. This is a quick assessment to measure your abilities. As we do understand the time constraints can be a negative effect on everyones performance therefore we are more interested in the thinking process rather than the actual solution.</p>
    <p>While you are delivering your solition follow best practice and <b>SOLID principle.</b> When you extend the data structure consider using data relationships.</p>
    <p>You  have the following tasks to complete. Please note the III. is a bonus excercise. </p>
    <ul class="float-left">
        <li>I.   Payer entity is using the Name property as the identifier. Please suggest a bettter method of identify each payer entity and please explain your suggesion.</li>
        <li>II.  The application is still under construction, pleae help us to implement the Edit view for the Payer grid by making a link in each row corresponting to the enditing Payer. In order to get the data you have to implement the IRepository interface in the PayerRepository. Lastly please create a view to Display the data in editable format and be ready for the next stage develpment.</li>
        <li>III. Please alter the IRepository to have Update method in it, implement the method and finish off the Edit functionality. Please pay attention to not breaking existing functinality.</li>
    </ul>
</div>

PayersPayment/Views/Payers/Index.cshtml
@model PayerViewModelList
@{
    ViewData["Title"] = "Payers Page";
}

<div class="text-center">
    <h3>The Payers List</h3>
    <div class="table-responsive">
        <table class="table table-hover">
            <th>Name</th>
            <th>Geneder</th>
            <th>Age</th>
            <th>Address</th>
            <tbody>
                @for (int i = 0; i < Model.Items.Count; i++)
                {
                <tr>
                    <td>@Html.Raw(Model.Items.ToArray()[i].Name)</td>
                    @Html.ActionLink("Edit", "Edit", new { name = "name" })
                    <td>@Html.Raw(Model.Items.ToArray()[i].Geneder)</td>
                    @Html.ActionLink("Edit", "Edit", new { name = "name" })
                    <td>@Html.Raw(Model.Items.ToArray()[i].Age)</td>
                    @Html.ActionLink("Edit", "Edit", new { name = "name" })
                    <td>@Html.Raw(Model.Items.ToArray()[i].Address)</td>

                </tr>
                }
            </tbody>
        </table>
    </div>
    </div>

PayersPayment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Payers Payments</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Payers Payments</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <div class="float-right">
                        <ul class="navbar-nav flex-grow-1">
                            @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>*@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Payers" asp-action="Index">Payers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Payers Payments - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>